### ISSUE TITLE
cc12m_filtered.index 를 찾지 못하겠습니다.

### ISSUE THREAD

**Issue by ksk0050** [AIRC-KETI/KE-T5-Vision#1]
cc12m_filtered_exhaustive.index는 있던데,
cc12m_filtered.index는 찾지 못하겠습니다.

**Comment by kimsan0622** [comment]
cc12m_filtered.index 는예시로 해놓은 것입니다.

CPU를 사용하실 경우,
- cc12m_filtered_exhaustive.index
- cc12m_filtered_OPQ64_256-IVF262144_HNSW32-PQ64.index
- cc12m_filtered_OPQ192_768-IVF262144_HNSW32-PQ192.index
를 사용하시고,

GPU를 사용하실 경우
fvecs 파일들을 사용하시면 됩니다.

cc12m_filtered_exhaustive.index: encoder의 output으로 나온 vector를 그대로 사용 (fvecs를 직접 사용하는 것과 차이가 없음)
cc12m_filtered_OPQ64_256-IVF262144_HNSW32-PQ64.index, cc12m_filtered_OPQ192_768-IVF262144_HNSW32-PQ192.index:  OPQ transformation을 통하여 vector 크기를 줄임. product quantization + linear projection을 통한 압축.  exhaustive보다 성능은 약간 낮으나 용량이 작음.
